src/apps/transactions/urls.py
from django.urls import path
from . import views

app_name = 'transactions'

urlpatterns=[
    path('deposito/', views.create_deposit, name='deposito'),
    path('transferencia/', views.create_transfer, name='transferencia'),

    #Reason
    path('reason/', views.create_reason, name='motivo')
]

src/apps/users/urls.py
from django.urls import path
from django.contrib.auth import views as views_django
from .views import auth_view, profile_view, transaction_view

from django.conf import settings
from django.conf.urls.static import static

app_name = 'users'

urlpatterns=[
    #USER
    path('login/', auth_view.login, name='login'),
    path('register/', auth_view.register, name="register"),
    path('logout/', views_django.logout_then_login, name='logout'),
    path('all-users/', auth_view.user_list, name='user_list'),
    path('desactivate/<int:user_id>/', auth_view.desactivate_user, name='desactivate_user'),

    #PROFILE
    path('perfil/', profile_view.view_profile, name='profile'),
    path('perfil/editar', profile_view.update_profile, name='update'),
    path('edit_user/<int:user_id>/', profile_view.edit_user, name='edit_user'),

    #TRANSACTIONS
    path('perfil/historial', transaction_view.transaction_history, name='historial'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.inicio, name='home'),
    path('usuarios/', include("apps.users.urls")),
    path('transacciones/', include('apps.transactions.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/home.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <h1>Nombre del usuario: {{user.first_name}}</h1>
        <h2>Saldo del usuario: {{user.balance}}</h2>

        <p> <a href="{% url 'users:profile' %}">ver perfil</a> </p> 

        <p> <a href="{% url 'users:user_list' %}">listar usuarios</a> </p> 

        <p> <a href="{% url 'transactions:deposito' %}">depositar</a> </p> 

        <p> <a href="{% url 'transactions:transferencia' %}">transferir</a> </p> 

        <p> <a href="{% url 'users:historial' %}">ver historial</a> </p> 

        <p> <a href="{% url 'transactions:motivo' %}">agregar motivo</a> </p>

        <p> <a href="{% url 'users:login' %}">iniciar sesion</a> </p>

        {% if user.is_authenticated %}
            <form method="POST" action="{% url 'users:logout' %}">
                {% csrf_token %}
                <button type="submit">Cerrar sesión</button>
            </form>
        {% else %}
            <p> <a href="{% url 'users:register' %}">registrarse</a> </p>
        {% endif %}
        
    </body>
</html>